parameters:


services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Module\Auth\:
        resource: '../../'
        exclude:
            - '../../Domain/Entity'
            - '../../Infrastructure/config'
