<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260322095717 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create maintenance_category table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE maintenance_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_18341DEC989D9B62 ON maintenance_category (slug)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE maintenance_category');
    }
}