<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260322095718 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create maintenance table with foreign keys to car_cars and maintenance_category';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE maintenance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description TEXT DEFAULT NULL, odometer INT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, amount NUMERIC(10, 5) NOT NULL, car_id INT NOT NULL, category_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2F84F8E9C3C6F69F ON maintenance (car_id)');
        $this->addSql('CREATE INDEX IDX_2F84F8E912469DE2 ON maintenance (category_id)');
        $this->addSql('ALTER TABLE maintenance ADD CONSTRAINT FK_2F84F8E9C3C6F69F FOREIGN KEY (car_id) REFERENCES car_cars (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE maintenance ADD CONSTRAINT FK_2F84F8E912469DE2 FOREIGN KEY (category_id) REFERENCES maintenance_category (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE maintenance DROP CONSTRAINT FK_2F84F8E9C3C6F69F');
        $this->addSql('ALTER TABLE maintenance DROP CONSTRAINT FK_2F84F8E912469DE2');
        $this->addSql('DROP TABLE maintenance');
    }
}