<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260321201621 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add cars table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE car_cars (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, brand JSON NOT NULL, model JSON NOT NULL, registration_number VARCHAR(255) DEFAULT NULL, mileage INT NOT NULL, gas INT NOT NULL, status VARCHAR(255) NOT NULL, vin VARCHAR(255) DEFAULT NULL, registration_company VARCHAR(255) DEFAULT NULL, leasing_company VARCHAR(255) DEFAULT NULL, gps VARCHAR(255) DEFAULT NULL, registration_document VARCHAR(255) DEFAULT NULL, insurance_document VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE car_cars');
    }
}
